
_db_path='database'
_db_path+'/fruits.json',
_db_path+'/casa_electronicos.json',
_db_path+'/casa_lavandaria.json',

json_dbs=[
      'databases/casa_loicas.json',
      'databases/casa_plastico.json',
      'databases/limpeza_8.json',
      'databases/limpeza_7.json',
      'databases/limpeza.json',
      'databases/lacticinios-yougurt-2.json',
      'databases/lacticinios-frangos.json',
      'databases/limpeza_2.json',
      # 'databases/casa_electronicos.json',
      'databases/limpeza_9.json',
      'databases/bebe2.json',
      'databases/lacticinios1.json',
      'databases/casa_lavandaria.json',
      'databases/limpeza_4.json',
      'databases/electrodomestic2.json',
      'databases/lacticinios-yougurt-1.json',
      'databases/limpeza_3.json',
      'databases/casa_cozinha_1.json',
      'databases/electrodomestic.json',
      'databases/electrodomestic3.json',
      'databases/lacticinios4.json',
      # 'databases/casa_cozinha_0.json',
      'databases/limpeza_10.json',
      # 'databases/novos.json',
      'databases/limpeza_6.json',
      'databases/limpeza_5.json',
      'databases/casa_quarto.json',
      'databases/bebe0.json',
      'databases/lacticinios2.json',
      'databases/casa_plastico0.json',
      # 'databases/fruits.json',
      'databases/lacticinios-manteiga.json']
